from __future__ import annotations

CONTRACT_TYPE_KEYWORDS: dict[str, tuple[str, ...]] = {
    "employment_agreement": (
        "employee",
        "employer",
        "salary",
        "probation",
        "hr",
        "joining date",
        "employment",
    ),
    "legal_services_agreement": (
        "legal services agreement",
        "law firm",
        "client",
        "attorney",
        "legal services",
        "retainer",
        "billing statement",
        "hourly rates",
        "discharge of law firm",
        "attorney-client",
    ),
    "government_empanelment": (
        "empanelment",
        "tender",
        "request for proposal",
        "rfp",
        "government",
        "authority",
        "department",
        "blacklisting",
        "debarment",
        "performance review",
        "no guaranteed work",
        "work order",
    ),
    "employment_bond": (
        "service bond",
        "bond period",
        "training cost",
        "liquidated damages",
        "leave before",
        "minimum service",
    ),
    "rental_agreement": (
        "landlord",
        "tenant",
        "rent",
        "security deposit",
        "premises",
        "lease",
        "lock in",
        "owner",
        "demised premises",
        "tenancy",
    ),
    "nda": (
        "non-disclosure",
        "confidential information",
        "disclosing party",
        "receiving party",
        "confidentiality",
    ),
    "loan_agreement": (
        "loan",
        "borrower",
        "lender",
        "interest",
        "repayment",
        "default",
        "emi",
    ),
    "freelance_contract": (
        "freelancer",
        "client",
        "deliverables",
        "milestone",
        "invoice",
        "scope of work",
    ),
    "service_agreement": (
        "service provider",
        "service level",
        "scope of services",
        "support",
        "maintenance",
    ),
    "software_saas_agreement": (
        "software",
        "saas",
        "subscription",
        "license",
        "uptime",
        "service level agreement",
        "sla",
        "data protection",
        "subprocessor",
        "data return",
        "data deletion",
    ),
    "vendor_agreement": (
        "vendor",
        "purchase order",
        "supply",
        "delivery",
        "procurement",
    ),
    "partnership_agreement": (
        "partnership",
        "partner",
        "profit sharing",
        "capital contribution",
        "management rights",
        "dissolution",
    ),
    "internship_agreement": (
        "intern",
        "internship",
        "stipend",
        "mentor",
        "training program",
    ),
}

CLAUSE_DEFINITIONS: dict[str, dict[str, str | tuple[str, ...]]] = {
    "termination": {
        "description": "Explains how either party can end the agreement and related consequences.",
        "keywords": (
            "termination",
            "terminate",
            "discharge",
            "withdraw",
            "expiry",
            "rescind",
            "end this agreement",
            "termination for cause",
            "termination without cause",
            "cancel this agreement",
        ),
    },
    "notice_period": {
        "description": "Defines required advance notice duration before resignation or termination.",
        "keywords": ("notice period", "prior notice", "days notice", "written notice", "notice"),
    },
    "scope_of_services": {
        "description": "Defines what work, services, deliverables, or representation is included.",
        "keywords": (
            "scope of services",
            "legal services",
            "services covered",
            "services not covered",
            "representation",
            "deliverables",
            "engagement",
        ),
    },
    "penalty": {
        "description": "Defines damages, fines, or penalties for breach or early exit.",
        "keywords": (
            "penalty",
            "liquidated damages",
            "penal",
            "damages",
            "fine",
            "forfeit",
            "breach cost",
            "early exit charge",
        ),
    },
    "bond": {
        "description": "Defines service bond requirements and bond amount for early exit.",
        "keywords": ("bond", "bond period", "service bond", "minimum service period", "bond amount"),
    },
    "confidentiality": {
        "description": "Defines confidentiality obligations and handling of confidential information.",
        "keywords": ("confidentiality", "confidential", "non-disclosure", "nda", "proprietary"),
    },
    "non_compete": {
        "description": "Restricts working with competitors or engaging in competing business.",
        "keywords": ("non-compete", "competitor", "competing business", "restraint of trade"),
    },
    "non_solicitation": {
        "description": "Restricts solicitation of clients, employees, or business contacts.",
        "keywords": ("non-solicitation", "solicit", "poach", "induce", "clients or employees"),
    },
    "payment": {
        "description": "Defines payment terms, fees, invoices, and due dates.",
        "keywords": (
            "payment",
            "fees",
            "invoice",
            "due date",
            "compensation",
            "salary",
            "remuneration",
            "charges",
            "rent",
            "monthly rent",
            "license fee",
            "billing",
            "hourly rate",
            "rate schedule",
            "fee schedule",
            "schedule of fees",
            "price schedule",
            "retainer",
        ),
    },
    "refund": {
        "description": "Defines refund conditions, timelines, and deductions.",
        "keywords": ("refund", "refundable", "reimburse", "return amount", "settlement"),
    },
    "auto_renewal": {
        "description": "Defines automatic renewal behavior and cancellation window.",
        "keywords": ("auto-renewal", "automatically renew", "renewal term", "renewed automatically"),
    },
    "jurisdiction": {
        "description": "Defines governing law and court jurisdiction for disputes.",
        "keywords": ("jurisdiction", "governing law", "courts of", "venue", "laws of"),
    },
    "arbitration": {
        "description": "Defines arbitration process and dispute resolution method.",
        "keywords": ("arbitration", "arbitrator", "dispute resolution", "arbitral", "conciliation"),
    },
    "liability": {
        "description": "Defines liability limits, indemnity, and allocation of responsibility.",
        "keywords": (
            "liability",
            "indemnify",
            "indemnity",
            "limitation of liability",
            "hold harmless",
            "errors and omissions",
            "errors & omissions",
            "insurance",
            "guaranty",
        ),
    },
    "ip_rights": {
        "description": "Defines ownership and usage rights of intellectual property.",
        "keywords": (
            "intellectual property",
            "ip rights",
            "ownership of work",
            "copyright",
            "trademark",
        ),
    },
    "data_privacy": {
        "description": "Defines obligations around personal data handling and privacy safeguards.",
        "keywords": ("data privacy", "personal data", "data protection", "privacy", "gdpr"),
    },
    "license": {
        "description": "Defines software, content, or usage license scope and restrictions.",
        "keywords": ("license", "licensed software", "subscription", "permitted use", "usage rights"),
    },
    "service_level": {
        "description": "Defines uptime, service levels, support, and performance commitments.",
        "keywords": ("service level", "sla", "uptime", "availability", "support", "response time"),
    },
    "audit_rights": {
        "description": "Defines inspection, audit, record access, and verification rights.",
        "keywords": ("audit", "inspection", "records", "books", "verify compliance"),
    },
    "compliance": {
        "description": "Defines legal, regulatory, policy, or authority compliance obligations.",
        "keywords": (
            "compliance",
            "applicable laws",
            "regulations",
            "policy",
            "blacklisting",
            "debarment",
            "statutory",
        ),
    },
    "assignment": {
        "description": "Defines assignment, delegation, subcontracting, and transfer rights.",
        "keywords": ("assignment", "assign", "delegate", "subcontract", "transfer"),
    },
    "performance_obligations": {
        "description": "Defines service performance, delivery, approval, and review obligations.",
        "keywords": (
            "performance",
            "deliver",
            "work order",
            "approval",
            "milestone",
            "acceptance criteria",
            "revision",
        ),
    },
    "security_deposit": {
        "description": "Defines security deposit amount, holding terms, and refund process.",
        "keywords": (
            "security deposit",
            "deposit amount",
            "deposit refund",
            "refundable deposit",
            "deposit",
        ),
    },
    "lock_in": {
        "description": "Defines lock-in period obligations and early exit constraints.",
        "keywords": ("lock-in", "lock in period", "minimum tenure", "early exit"),
    },
    "rent_escalation": {
        "description": "Defines rent increase schedule and escalation percentage.",
        "keywords": ("rent escalation", "rent increase", "increase in rent", "escalation"),
    },
    "maintenance": {
        "description": "Defines repair, maintenance, utilities, and upkeep responsibilities.",
        "keywords": (
            "maintenance",
            "repairs",
            "utilities",
            "electricity",
            "water charges",
            "meter",
            "welfare association",
        ),
    },
    "use_restrictions": {
        "description": "Restricts how property, services, or information may be used.",
        "keywords": (
            "use of premises",
            "purpose",
            "sublet",
            "assignment",
            "alterations",
            "not use",
        ),
    },
    "parties": {
        "description": "Identifies the parties entering into the contract.",
        "keywords": ("parties", "between", "by and between", "client", "provider", "company"),
    },
    "document_title": {
        "description": "Identifies the document or agreement name.",
        "keywords": ("agreement", "contract", "document name", "title", "exhibit"),
    },
    "effective_date": {
        "description": "Defines the agreement date, effective date, or commencement date.",
        "keywords": ("effective date", "agreement date", "commencement date", "dated as of"),
    },
    "exclusivity": {
        "description": "Restricts one party from dealing with competitors or alternative partners.",
        "keywords": ("exclusive", "exclusivity", "sole provider", "sole distributor", "exclusive right"),
    },
    "pricing_parity": {
        "description": "Requires pricing, terms, or benefits to match or beat third-party terms.",
        "keywords": ("most favored", "most favoured", "mfN", "price parity", "no less favorable"),
    },
    "transfer_restrictions": {
        "description": "Defines rights of first refusal, offer, negotiation, or transfer limits.",
        "keywords": (
            "right of first refusal",
            "right of first offer",
            "right of first negotiation",
            "rofr",
            "rofo",
            "rofn",
        ),
    },
    "software_escrow": {
        "description": "Defines source-code escrow or release conditions.",
        "keywords": ("source code escrow", "escrow", "source code release", "deposit materials"),
    },
    "warranty": {
        "description": "Defines warranties, warranty duration, disclaimers, and warranty remedies.",
        "keywords": ("warranty", "warranties", "warranty period", "disclaimer", "as is"),
    },
    "third_party_rights": {
        "description": "Defines third-party beneficiary rights or exclusions.",
        "keywords": ("third party beneficiary", "third-party beneficiary", "no third party", "no third-party"),
    },
    "non_disparagement": {
        "description": "Restricts negative statements or disparagement about a party.",
        "keywords": ("non-disparagement", "disparage", "negative statement", "public criticism"),
    },
}

EXPECTED_CLAUSES_BY_CONTRACT: dict[str, tuple[str, ...]] = {
    "employment_agreement": (
        "termination",
        "notice_period",
        "payment",
        "confidentiality",
        "jurisdiction",
    ),
    "legal_services_agreement": (
        "scope_of_services",
        "payment",
        "termination",
        "confidentiality",
        "liability",
    ),
    "government_empanelment": (
        "scope_of_services",
        "payment",
        "termination",
        "compliance",
        "performance_obligations",
    ),
    "employment_bond": (
        "bond",
        "penalty",
        "termination",
        "notice_period",
        "jurisdiction",
    ),
    "rental_agreement": (
        "payment",
        "security_deposit",
        "termination",
        "maintenance",
        "use_restrictions",
    ),
    "nda": ("confidentiality", "termination", "jurisdiction", "liability"),
    "loan_agreement": ("payment", "penalty", "termination", "jurisdiction", "liability"),
    "freelance_contract": ("payment", "termination", "ip_rights", "confidentiality", "liability"),
    "service_agreement": ("payment", "termination", "liability", "data_privacy", "jurisdiction"),
    "software_saas_agreement": (
        "payment",
        "license",
        "service_level",
        "data_privacy",
        "liability",
        "termination",
    ),
    "vendor_agreement": ("payment", "termination", "liability", "jurisdiction"),
    "partnership_agreement": ("payment", "termination", "liability", "jurisdiction"),
    "internship_agreement": (
        "termination",
        "notice_period",
        "confidentiality",
        "ip_rights",
    ),
}

RECOMMENDED_CLAUSES_BY_CONTRACT: dict[str, tuple[str, ...]] = {
    "employment_agreement": ("jurisdiction", "liability"),
    "legal_services_agreement": ("jurisdiction", "arbitration", "data_privacy"),
    "government_empanelment": (
        "jurisdiction",
        "arbitration",
        "liability",
        "audit_rights",
        "assignment",
    ),
    "employment_bond": ("refund", "liability"),
    "rental_agreement": ("lock_in", "rent_escalation", "jurisdiction", "arbitration"),
    "nda": ("liability", "arbitration"),
    "loan_agreement": ("arbitration",),
    "freelance_contract": ("jurisdiction", "arbitration"),
    "service_agreement": ("arbitration",),
    "software_saas_agreement": ("audit_rights", "assignment", "confidentiality"),
    "vendor_agreement": ("arbitration",),
    "partnership_agreement": ("arbitration", "assignment"),
    "internship_agreement": ("jurisdiction",),
}

CONTRACT_TYPE_LABELS: dict[str, str] = {
    "employment_agreement": "Employment Agreement",
    "legal_services_agreement": "Legal Services Agreement",
    "government_empanelment": "Government / Empanelment / Tender Agreement",
    "employment_bond": "Employment Bond",
    "rental_agreement": "Rental Agreement",
    "nda": "NDA / Confidentiality Agreement",
    "loan_agreement": "Loan Agreement",
    "freelance_contract": "Freelance Contract",
    "service_agreement": "Service Agreement",
    "software_saas_agreement": "Vendor / SaaS / Software Agreement",
    "vendor_agreement": "Vendor Agreement",
    "partnership_agreement": "Partnership Agreement",
    "internship_agreement": "Internship Agreement",
    "legal_template_collection": "Legal Template Collection",
}

DOCUMENT_ANALYSIS_PROFILES: dict[str, dict[str, object]] = {
    "rental_agreement": {
        "purpose": "Use or occupation of property in exchange for rent or related charges.",
        "likely_user_role": "tenant or owner",
        "stronger_party": "usually owner/landlord if terms are non-negotiable",
        "missing_clause_risk": {
            "payment": "medium",
            "security_deposit": "medium",
            "termination": "medium",
            "maintenance": "medium",
            "use_restrictions": "low",
        },
    },
    "employment_agreement": {
        "purpose": "Employment terms, compensation, obligations, and exit conditions.",
        "likely_user_role": "employee",
        "stronger_party": "usually employer/company",
        "missing_clause_risk": {
            "termination": "medium",
            "notice_period": "medium",
            "payment": "medium",
            "confidentiality": "low",
            "jurisdiction": "low",
        },
    },
    "employment_bond": {
        "purpose": "Employment with minimum service or training-cost recovery obligations.",
        "likely_user_role": "employee",
        "stronger_party": "usually employer/company",
        "missing_clause_risk": {
            "bond": "high",
            "penalty": "high",
            "termination": "medium",
            "notice_period": "medium",
            "jurisdiction": "low",
        },
    },
    "freelance_contract": {
        "purpose": "Independent work, deliverables, acceptance, payment, and IP ownership.",
        "likely_user_role": "freelancer or client",
        "stronger_party": "often client if payment and acceptance terms are unilateral",
        "missing_clause_risk": {
            "payment": "medium",
            "termination": "medium",
            "ip_rights": "medium",
            "confidentiality": "low",
            "liability": "high",
        },
    },
    "service_agreement": {
        "purpose": "Services, performance obligations, fees, liability, and termination.",
        "likely_user_role": "customer or service provider",
        "stronger_party": "depends on template owner",
        "missing_clause_risk": {
            "payment": "medium",
            "termination": "medium",
            "liability": "high",
            "data_privacy": "medium",
            "jurisdiction": "medium",
        },
    },
    "software_saas_agreement": {
        "purpose": "Software license, SaaS access, support, security, and data handling.",
        "likely_user_role": "customer or vendor",
        "stronger_party": "usually software vendor/provider",
        "missing_clause_risk": {
            "license": "high",
            "service_level": "medium",
            "data_privacy": "high",
            "liability": "high",
            "termination": "medium",
            "payment": "medium",
        },
    },
    "legal_services_agreement": {
        "purpose": "Legal representation scope, fees, billing, withdrawal, and client duties.",
        "likely_user_role": "client",
        "stronger_party": "usually law firm because it drafts engagement terms",
        "missing_clause_risk": {
            "scope_of_services": "medium",
            "payment": "medium",
            "termination": "medium",
            "confidentiality": "low",
            "liability": "medium",
        },
    },
    "government_empanelment": {
        "purpose": "Eligibility/empanelment to receive government or authority work orders.",
        "likely_user_role": "vendor, consultant, agency, or service provider",
        "stronger_party": "government authority / department",
        "missing_clause_risk": {
            "scope_of_services": "medium",
            "payment": "medium",
            "termination": "high",
            "compliance": "high",
            "performance_obligations": "medium",
        },
    },
    "vendor_agreement": {
        "purpose": "Supply, procurement, delivery, payment, liability, and termination.",
        "likely_user_role": "vendor or buyer",
        "stronger_party": "often buyer/procuring company",
        "missing_clause_risk": {
            "payment": "medium",
            "termination": "medium",
            "liability": "high",
            "jurisdiction": "medium",
        },
    },
    "nda": {
        "purpose": "Protection and controlled use of confidential information.",
        "likely_user_role": "disclosing or receiving party",
        "stronger_party": "depends on whether NDA is one-way or mutual",
        "missing_clause_risk": {
            "confidentiality": "high",
            "termination": "low",
            "jurisdiction": "low",
            "liability": "medium",
        },
    },
    "loan_agreement": {
        "purpose": "Loan amount, repayment, interest, default, and recovery rights.",
        "likely_user_role": "borrower or lender",
        "stronger_party": "usually lender",
        "missing_clause_risk": {
            "payment": "high",
            "penalty": "medium",
            "termination": "medium",
            "jurisdiction": "medium",
            "liability": "medium",
        },
    },
}

RISK_LEVEL_SCORES: dict[str, int] = {
    "critical": 82,
    "high": 62,
    "medium": 38,
    "low": 18,
    "informational": 8,
}
